### ISSUE TITLE
code:generate 命令报错Declaration of Hyperf\Amqp\AMQPConnection::wait_channel($channel_id, $timeout = 0) must be compatible with PhpAmqpLib\Connection\AbstractConnection::wait_channel(int $channel_id, $timeout = 0): PhpAmqpLib\Channel\Frame 

### ISSUE THREAD

**Issue by palfeline** [hyperf/code-generator#8]
hyperf 从2.2升级至3.0
执行如下命令后
php bin/hyperf.php code:generate -D app
报错
PHP Fatal error:  Declaration of Hyperf\Amqp\AMQPConnection::wait_channel($channel_id, $timeout = 0) must be compatible with PhpAmqpLib\Connection\AbstractConnection::wait_channel(int $channel_id, $timeout = 0): PhpAmqpLib\Channel\Frame in /data/xxxx/vendor/hyperf/amqp/src/AMQPConnection.php on line 288

Fatal error: Declaration of Hyperf\Amqp\AMQPConnection::wait_channel($channel_id, $timeout = 0) must be compatible with PhpAmqpLib\Connection\AbstractConnection::wait_channel(int $channel_id, $timeout = 0): PhpAmqpLib\Channel\Frame in /data/xxxx/vendor/hyperf/amqp/src/AMQPConnection.php on line 288

PHP Fatal error:  Uncaught PhpParser\Error: Syntax error, unexpected T_NS_SEPARATOR, expecting T_VARIABLE on line 21 in /data/xxxx/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:321

Stack trace:
#0 /data/xxxx/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(162): PhpParser\ParserAbstract->doParse()
#1 /data/xxxx/vendor/hyperf/code-generator/src/Ast.php(37): PhpParser\ParserAbstract->parse()
#2 /data/xxxx/vendor/hyperf/code-generator/src/CodeGenerator.php(25): Hyperf\CodeGenerator\Ast->generate()
#3 /data/xxxx/vendor/hyperf/code-generator/src/Command/CodeGenerateCommand.php(60): Hyperf\CodeGenerator\CodeGenerator->generate()
#4 /data/xxxx/vendor/hyperf/utils/src/Functions.php(279): Hyperf\CodeGenerator\Command\CodeGenerateCommand->handle()
#5 /data/xxxx/vendor/hyperf/command/src/Command.php(444): call()
#6 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#7 {main}
  thrown in /data/xxxx/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 321
php 版本 8.2.3

**Comment by huangzhhui** [comment]
请按照 issue 模板要求提交 issue

**Comment by palfeline** [comment]
请问模版在哪里。。。实在没有找到。。。

**Comment by palfeline** [comment]
注掉报错的语句后OK了，应该是adqp的问题，麻烦关掉吧

**Comment by limingxinleo** [comment]
rabbitmq的包的问题
